Organizations:
    - &OrdererOrg
        Name: PuniOrdererMSP
        ID: PuniOrdererMSP
        MSPDir: ./crypto-config/ordererOrganizations/example.com/msp

    - &Org1
        Name: Bank1MSP
        ID: Bank1MSP
        MSPDir: ./crypto-config/peerOrganizations/Bank1.co.in/msp
        AnchorPeers:
            - Host: peer0.bank1.co.in
              Port: 7051

    - &Org2
        Name: Bank2MSP
        ID: Bank2MSP
        MSPDir: ./crypto-config/peerOrganizations/Bank2.azure.com/msp
        AnchorPeers:
            - Host: peer0.bank2.azure.com
              Port: 7051

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults
    Organizations:

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - puniorderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 98 MB
        PreferredMaxBytes: 512 KB

    Kafka:
        Brokers:
            - 127.0.0.1:9092
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    TwoOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1
                    - *Org2
    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Org1
                - *Org2
